### PR TITLE
Python 3.9 is missing

### PR DESCRIPTION
**Pull request by ocefpaf**
Re-rendering it should take care of this.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Failing with:

```
Created temporary directory: /tmp/pip-unpack-v222c1tm
Building wheels for collected packages: dask-gateway-server
  Created temporary directory: /tmp/pip-wheel-vnztoxhl
  Building wheel for dask-gateway-server (setup.py) ...   Destination directory: /tmp/pip-wheel-vnztoxhl
  Running command /home/conda/feedstock_root/build_artifacts/dask-gateway_1627329318440/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ad4tk5zy/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ad4tk5zy/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-vnztoxhl
  running bdist_wheel
  running build
  running build_proxy
  go: go.mod file not found in current directory or any parent directory; see 'go help modules'
error
  ERROR: Failed building wheel for dask-gateway-server
```

**Comment by bollwyvl** [comment]
Maybe `GO111MODULE=off`? https://blog.golang.org/go116-module-changes#TOC_2.

**Comment by ocefpaf** [comment]
> Maybe `GO111MODULE=off`? https://blog.golang.org/go116-module-changes#TOC_2.

Awesome! That worked!! Thanks @bollwyvl!!!

**Comment by bollwyvl** [comment]
It works.... _today_. :rofl:   But the writing is on the wall... love those _change the entire build posture on a .x release_ threats...

**Pull request merged**
