### PR TITLE
Add maintainers, add linux-aarch64, fix entry_points, build for py38-310

### LINKED ISSUE #27: Multiple issues to resolve for the 2022.4.0 release
As I've failed to resolve this myself, I've aimed to summarize known issues we have to fix leading to a release here in conda-forge. PRs to resolve things in this feedstock very much appreciated.

## Goal definition

- Ensure we are multiple maintainers of this feedstock (#22).
- Feedstock's CI to go green for `dask-gateway` and `dask-gateway-server` version `2022.4.0` on PyPI.
- Build _base_ and _extras_ packages:
  - _base_ packages
    - [`dask-gateway`](https://github.com/conda-forge/dask-gateway-feedstock/blob/1232aa55de22f25072aca689100f1857c7de4771/recipe/meta.yaml#L36-L47)
      Published as [`py3-none-any` on `PyPI`](https://pypi.org/project/dask-gateway/#files)
    - [`dask-gateway-server`](https://github.com/conda-forge/dask-gateway-feedstock/blob/1232aa55de22f25072aca689100f1857c7de4771/recipe/meta.yaml#L49-L69)
      Published as [`py3-none-[...]` on `PyPI`](https://pypi.org/project/dask-gateway-server/#files) where `[...]` is the four variations of combining the choices of linux/osx and amd64/arm64.
  - _extras_ packages (related to `extras_require` in respective setup.py file)
    - [`dask-gateway-kerberos`](https://github.com/conda-forge/dask-gateway-feedstock/blob/1232aa55de22f25072aca689100f1857c7de4771/recipe/meta.yaml#L36-L47)
    - [`dask-gateway-server-[jobqueue|local|slurm|yarn]`](https://github.com/conda-forge/dask-gateway-feedstock/blob/1232aa55de22f25072aca689100f1857c7de4771/recipe/meta.yaml#L78-L140)
    Note that getting these packages built may not be essential and a possible compromise.

### Python 3.10 / Py 38+ / No CPython / Included golang binary

Right now we publish one version per Python version (but not for Python 3.10). Preferably we would stop doing variations based on Python version as there is no need. But, we still need variations for `dask-gateway-server` which bundles a Golang executable binary that is to be made available for linux-amd64 / linux-arm64 / osx-amd64 / osx-arm64.

### Arm64 support

In PyPI, we have with the 2022.4.0 release created wheels for `dask-gateway-server` built for Linux and Mac, both for amd64 and arm64. Previously, we didn't have wheels for arm64. I consider it an optional success if we manage to package for that as well, but I think osx-arm64 requires cross-compiling which may make the configuration need to adjust significantly.

Cross compiling for `dask-gateway-server`'s golang binary can be done with `GOOS` and `GOARCH`, see https://github.com/dask/dask-gateway/blob/d0cb34d5a21d50998d157f7ede432eb9f0726d9b/dask-gateway-server/setup.py#L140-L156.

### Decision about the _extras_ packages

Would we be willing to stop providing variations for these? I think for `dask-gateway` we could simply declare `build.noarch=python` and we would be fine for all architectures, but by adjusting the dependencies based on windows or not, we may not be able to as seen in `dask-gateway-kerberos`. Similarly for `dask-gateway-server`, should we really provide all kinds of variations based on `extras_require`? I've failed to find documentation on this practice or if there are options on mapping `extras_require` to a conda-forge feedstock.

### PR DESCRIPTION
**Pull request by consideRatio**
## Summary

When this is merged, a new build will be made and the 2022.4.0 release will be fully out the door.

- **adds maintainers to this feedstock**
  - closes #22
  - closes #25
- **package the 2022.4.0 release in conda-forge**
  - closes #27
- **package for Python 3.8 to Python 3.10**
  - closes #21
- **adds some documentation**

While we are at it and closing all other issues and PRs besides #19, I suggest we close that old PR as well.

## Not included

- Builds for osx-arm64. I've failed with this because I've generally failed to cross compile and there aren't any native osx-arm64 workers we can use yet.

---

@jcrist @martindurant @jacobtomlinson @TomAugspurger all tests are passing! This is ready for review/merge.

### CODE REVIEW

**Review by jacobtomlinson — APPROVED** [review]
This looks great!

I think only @jcrist can merge this for now.

**Review by TomAugspurger — APPROVED** [review]

**Review by martindurant — APPROVED** [review]

**Comment by consideRatio** [comment]
With this merged, I hope to see us update some pangeo docker stacks image, and then also dask/helm-chart having the daskhub helm chart that wraps both jupyterhub+dask-gateway with some additional configuration.

**Comment by consideRatio** [comment]
@jcrist I hope you don't mind me nudging you about this, I hope to followup and verify this works all the way before going on a vacation in the end of the week.

**Review by jcrist — APPROVED** [review]
Thanks @consideRatio! This looks good to me.

**Comment by consideRatio** [comment]
Wieee thanks everyone! I've confirmed that the install works and seem to ship with the desired golang executable compiled for the correct platform.

**Pull request merged**
